dataset:
  transformations:
    -
      name: ItalicityAngle
      apply_probability: 0.8
      min_angle_degrees: -35
      max_angle_degrees: 35
    -
      name: ну 
    -
      name: EquidistantResample
      delta: 0.05
    -
      name: BaselineInclinationAngle
      apply_probability: 0.8
      min_angle_radians: -0.3
      max_angle_radians: 0.3
    -
      name: Normalize
    -
      name: CalculateDifferencesBetweenAdjacentPoints
  to_lowercase: False

train:
  batch_size: 8
  lr: 0.0001
  epochs: 10000
  dataloader_num_workers: 8

decoder:
  num_processes: 10

val:
  batch_size: 128
  frequency: 15
  dataloader_num_workers: 8

device: cuda:4
num_images_visualize_before_train: 50